local config = {
    [1] = {
        id=1,
        unableTips="<font color='#ffff00' size='16' >幽门:未通</font><br><br><font color='#ffffff' size='16' >通过“舒经活络丸”打通</font><br><font color='#ffffff' size='16' >打通穴后获得防御上限+3</font>",
        name="幽门",
        openTips="<font color='#ff0000' size='16' >幽门:已打通</font><br><font color='#ffffff' size='16' >已获得防御上限+3</font>",
    },
    [2] = {
        id=2,
        unableTips="<font color='#ffff00' size='16' >通谷:未通</font><br><br><font color='#ffffff' size='16' >通过“舒经活络丸”打通</font><br><font color='#ffffff' size='16' >打通穴后获得魔御上限+3</font>",
        name="通谷",
        openTips="<font color='#ff0000' size='16' >通谷:已打通</font><br><font color='#ffffff' size='16' >已获得魔御上限+3</font>",
    },
    [3] = {
        id=3,
        unableTips="<font color='#ffff00' size='16' >商曲:未通</font><br><br><font color='#ffffff' size='16' >通过“舒经活络丸”打通</font><br><font color='#ffffff' size='16' >打通穴后获得防御下限+3</font>",
        name="商曲",
        openTips="<font color='#ff0000' size='16' >商曲:已打通</font><br><font color='#ffffff' size='16' >已获得防御下限+3</font>",
    },
    [4] = {
        id=4,
        unableTips="<font color='#ffff00' size='16' >四满:未通</font><br><br><font color='#ffffff' size='16' >通过“舒经活络丸”打通</font><br><font color='#ffffff' size='16' >打通穴后获得魔御下限+3</font>",
        name="四满",
        openTips="<font color='#ff0000' size='16' >四满:已打通</font><br><font color='#ffffff' size='16' >已获得魔御下限+3</font>",
    },
    [5] = {
        id=5,
        unableTips="<font color='#ffff00' size='16' >横骨:未通</font><br><br><font color='#ffffff' size='16' >通过“舒经活络丸”打通</font><br><font color='#ffffff' size='16' >打通穴后获得防御上限+2</font>",
        name="横骨",
        openTips="<font color='#ff0000' size='16' >横骨:已打通</font><br><font color='#ffffff' size='16' >已获得防御上限+2</font>",
    },
    [6] = {
        id=6,
        unableTips="<font color='#ffff00' size='16' >晴明:未通</font><br><br><font color='#ffffff' size='16' >舒经活络丸 50%几率打通</font><br><font color='#ffffff' size='16' >打通穴后获得魔御上限+2</font>",
        name="晴明",
        openTips="<font color='#ff0000' size='16' >晴明:已打通</font><br><font color='#ffffff' size='16' >已获得魔御上限+2</font>",
    },
    [7] = {
        id=7,
        unableTips="<font color='#ffff00' size='16' >盘缺:未通</font><br><br><font color='#ffffff' size='16' >舒经活络丸 50%几率打通</font><br><font color='#ffffff' size='16' >打通穴后获得防御下限+2</font>",
        name="盘缺",
        openTips="<font color='#ff0000' size='16' >盘缺:已打通</font><br><font color='#ffffff' size='16' >已获得防御下限+2</font>",
    },
    [8] = {
        id=8,
        unableTips="<font color='#ffff00' size='16' >交信:未通</font><br><br><font color='#ffffff' size='16' >舒经活络丸 50%几率打通</font><br><font color='#ffffff' size='16' >打通穴后获得魔御下限+2</font>",
        name="交信",
        openTips="<font color='#ff0000' size='16' >交信:已打通</font><br><font color='#ffffff' size='16' >已获得魔御下限+2</font>",
    },
    [9] = {
        id=9,
        unableTips="<font color='#ffff00' size='16' >照海:未通</font><br><br><font color='#ffffff' size='16' >舒经活络丸 50%几率打通</font><br><font color='#ffffff' size='16' >打通穴后获得防御上限+1</font>",
        name="照海",
        openTips="<font color='#ff0000' size='16' >照海:已打通</font><br><font color='#ffffff' size='16' >已获得防御上限+1</font>",
    },
    [10] = {
        id=10,
        unableTips="<font color='#ffff00' size='16' >然谷:未通</font><br><br><font color='#ffffff' size='16' >舒经活络丸 50%几率打通</font><br><font color='#ffffff' size='16' >打通穴后获得魔御上限+1</font>",
        name="然谷",
        openTips="<font color='#ff0000' size='16' >然谷:已打通</font><br><font color='#ffffff' size='16' >已获得魔御上限+1</font>",
    },
    [11] = {
        id=11,
        unableTips="<font color='#ffff00' size='16' >廉泉:未通</font><br><br><font color='#ffffff' size='16' >舒经活络丸 30%几率打通</font><br><font color='#ffffff' size='16' >打通穴后获得防御下限+1</font>",
        name="廉泉",
        openTips="<font color='#ff0000' size='16' >廉泉:已打通</font><br><font color='#ffffff' size='16' >已获得防御下限+1</font>",
    },
    [12] = {
        id=12,
        unableTips="<font color='#ffff00' size='16' >期门:未通</font><br><br><font color='#ffffff' size='16' >舒经活络丸 30%几率打通</font><br><font color='#ffffff' size='16' >打通穴后获得魔御下限+1</font>",
        name="期门",
        openTips="<font color='#ff0000' size='16' >期门:已打通</font><br><font color='#ffffff' size='16' >已获得魔御下限+1</font>",
    },
    [13] = {
        id=13,
        unableTips="<font color='#ffff00' size='16' >府舍:未通</font><br><br><font color='#ffffff' size='16' >舒经活络丸 30%几率打通</font><br><font color='#ffffff' size='16' >打通穴后获得准确+3</font>",
        name="府舍",
        openTips="<font color='#ff0000' size='16' >府舍:已打通</font><br><font color='#ffffff' size='16' >已获得准确+3</font>",
    },
    [14] = {
        id=14,
        unableTips="<font color='#ffff00' size='16' >冲门:未通</font><br><br><font color='#ffffff' size='16' >舒经活络丸 30%几率打通</font><br><font color='#ffffff' size='16' >打通穴后获得敏捷+3</font>",
        name="冲门",
        openTips="<font color='#ff0000' size='16' >冲门:已打通</font><br><font color='#ffffff' size='16' >已获得敏捷+3</font>",
    },
    [15] = {
        id=15,
        unableTips="<font color='#ffff00' size='16' >筑宾:未通</font><br><br><font color='#ffffff' size='16' >舒经活络丸 30%几率打通</font><br><font color='#ffffff' size='16' >打通穴后获得准确+2</font>",
        name="筑宾",
        openTips="<font color='#ff0000' size='16' >筑宾:已打通</font><br><font color='#ffffff' size='16' >已获得准确+2</font>",
    },
    [16] = {
        id=16,
        unableTips="<font color='#ffff00' size='16' >承浆:未通</font><br><br><font color='#ffffff' size='16' >舒经活络丸 25%几率打通</font><br><font color='#ffffff' size='16' >打通穴后获得敏捷+2</font>",
        name="承浆",
        openTips="<font color='#ff0000' size='16' >承浆:已打通</font><br><font color='#ffffff' size='16' >已获得敏捷+2</font>",
    },
    [17] = {
        id=17,
        unableTips="<font color='#ffff00' size='16' >天突:未通</font><br><br><font color='#ffffff' size='16' >舒经活络丸 25%几率打通</font><br><font color='#ffffff' size='16' >打通穴后获得准确+1</font>",
        name="天突",
        openTips="<font color='#ff0000' size='16' >天突:已打通</font><br><font color='#ffffff' size='16' >已获得准确+1</font>",
    },
    [18] = {
        id=18,
        unableTips="<font color='#ffff00' size='16' >鸠尾:未通</font><br><br><font color='#ffffff' size='16' >舒经活络丸 25%几率打通</font><br><font color='#ffffff' size='16' >打通穴后获得敏捷+1</font>",
        name="鸠尾",
        openTips="<font color='#ff0000' size='16' >鸠尾:已打通</font><br><font color='#ffffff' size='16' >已获得敏捷+1</font>",
    },
    [19] = {
        id=19,
        unableTips="<font color='#ffff00' size='16' >气海:未通</font><br><br><font color='#ffffff' size='16' >舒经活络丸 25%几率打通</font><br><font color='#ffffff' size='16' >打通穴后获得HP值+1</font>",
        name="气海",
        openTips="<font color='#ff0000' size='16' >气海:已打通</font><br><font color='#ffffff' size='16' >已获得HP值+10</font>",
    },
    [20] = {
        id=20,
        unableTips="<font color='#ffff00' size='16' >曲骨:未通</font><br><br><font color='#ffffff' size='16' >舒经活络丸 25%几率打通</font><br><font color='#ffffff' size='16' >打通穴后获得MP值+1</font>",
        name="曲骨",
        openTips="<font color='#ff0000' size='16' >曲骨:已打通</font><br><font color='#ffffff' size='16' >已获得MP值+10</font>",
    },
    [21] = {
        id=21,
        unableTips="<font color='#ffff00' size='16' >神冲:未通</font><br><br><font color='#ffffff' size='16' >通过“奇经神冲丸”打通</font><br><font color='#ffffff' size='16' >可修炼提升斗转星移技能等级。</font>",
        name="神冲",
        openTips="<font color='#ff0000' size='16' >神冲:已打通</font><br><font color='#ffffff' size='16' >点击修炼奇经按钮，</font><br><font color='#ffffff' size='16' >提升斗转星移技能等级。</font>",
    },
    [22] = {
        id=22,
        unableTips="<font color='#ffff00' size='16' >夹脊:未通</font><br><br><font color='#ffffff' size='16' >通过“奇经夹脊丸”打通</font>",
        name="夹脊",
        openTips="<font color='#ff0000' size='16' >夹脊:已打通</font>",
    },
    [23] = {
        id=23,
        unableTips="<font color='#ffff00' size='16' >二百:未通</font><br><br><font color='#ffffff' size='16' >通过“奇经二百丸”打通</font>",
        name="二百",
        openTips="<font color='#ff0000' size='16' >二百:已打通</font>",
    },
    [24] = {
        id=24,
        unableTips="<font color='#ffff00' size='16' >八风:未通</font><br><br><font color='#ffffff' size='16' >通过“奇经八风丸”打通</font>",
        name="八风",
        openTips="<font color='#ff0000' size='16' >八风:已打通</font>",
    },
    [25] = {
        id=25,
        unableTips="<font color='#ffff00' size='16' >涌泉:未通</font><br><br><font color='#ffffff' size='16' >通过“奇经涌泉丸”打通</font>",
        name="涌泉",
        openTips="<font color='#ff0000' size='16' >涌泉:已打通</font>",
    },
}
return config
