local config = { 
	[1] = { 
		id=1,
		playerName="孟子",
		monsterName="[狂暴]尸魔王",
		mapName="龙族领地一层",
		itemID=60012,
		itemName="天师长袍",
		g_itemName="天师长袍-改名",
		mapX=321,
		mapY=548,
	},
	[2] = { 
		id=2,
		playerName="庄子",
		monsterName="[狂暴]骷髅王",
		mapName="龙族领地一层",
		itemID=60013,
		itemName="天尊头盔",
		mapX=321,
		mapY=548,
	},
	[3] = { 
		id=3,
		playerName="商鞅",
		monsterName="[狂暴]暗之血巨人",
		mapName="龙族领地一层",
		itemID=60014,
		itemName="天尊项链",
		mapX=321,
		mapY=548,
	},
	[4] = { 
		id=4,
		playerName="屈原",
		monsterName="[狂暴]暗之双头血魔",
		mapName="龙族领地一层",
		itemID=60015,
		itemName="天尊手镯",
		mapX=321,
		mapY=548,
	},
	[5] = { 
		id=5,
		playerName="项羽",
		monsterName="[狂暴]矿洞主宰",
		mapName="龙族领地一层",
		itemID=60016,
		itemName="天尊戒指",
		mapX=322,
		mapY=549,
	},
	[6] = { 
		id=6,
		playerName="仲舒",
		monsterName="[狂暴]地狱主宰·遗忘者",
		mapName="龙族领地一层",
		itemID=60017,
		itemName="天尊腰带",
		mapX=323,
		mapY=550,
	},
	[7] = { 
		id=7,
		playerName="相如",
		monsterName="[狂暴]地狱勾魂使·魄",
		mapName="龙族领地一层",
		itemID=60018,
		itemName="天尊道靴",
		mapX=324,
		mapY=551,
	},
	[8] = { 
		id=8,
		playerName="清照",
		monsterName="[狂暴]地狱勾魂使·噬",
		mapName="龙族领地一层",
		itemID=60019,
		itemName="骨玉权杖",
		mapX=325,
		mapY=552,
	},
	[9] = { 
		id=9,
		playerName="岳飞",
		monsterName="[狂暴]恶魔霸主",
		mapName="龙族领地一层",
		itemID=60020,
		itemName="法神披风",
		mapX=326,
		mapY=553,
	},
	[10] = { 
		id=10,
		playerName="弃疾",
		monsterName="[狂暴]暗之祖玛教主",
		mapName="龙族领地一层",
		itemID=60021,
		itemName="霓裳羽衣",
		mapX=21,
		mapY=33,
	},
	[11] = { 
		id=11,
		playerName="天祥",
		monsterName="[狂暴]暗之魔龙教主",
		mapName="龙族领地一层",
		itemID=60022,
		itemName="法神头盔",
		mapX=22,
		mapY=34,
	},
	[12] = { 
		id=12,
		playerName="思汗",
		monsterName="[狂暴]暗之牛魔王",
		mapName="龙族领地一层",
		itemID=60023,
		itemName="法神项链",
		mapX=23,
		mapY=35,
	},
	[13] = { 
		id=13,
		playerName="必烈",
		monsterName="[狂暴]掷斧骷髅",
		mapName="龙族领地一层",
		itemID=60024,
		itemName="法神手镯",
		mapX=24,
		mapY=36,
	},
	[14] = { 
		id=14,
		playerName="汉卿",
		monsterName="[狂暴]骷髅战士",
		mapName="龙族领地一层",
		itemID=60025,
		itemName="法神戒指",
		mapX=25,
		mapY=37,
	},
	[15] = { 
		id=15,
		playerName="道婆",
		monsterName="[狂暴]骷髅精灵",
		mapName="龙族领地一层",
		itemID=60026,
		itemName="法神腰带",
		mapX=26,
		mapY=38,
	},
	[16] = { 
		id=16,
		playerName="元璋",
		monsterName="[狂暴]骷髅锤兵",
		mapName="迷宫二层",
		itemID=60027,
		itemName="法神魔靴",
		mapX=27,
		mapY=39,
	},
	[17] = { 
		id=17,
		playerName="阳明",
		monsterName="[狂暴]恶魔使者",
		mapName="迷宫二层",
		itemID=60028,
		itemName="圣战勋章",
		mapX=28,
		mapY=40,
	},
	[18] = { 
		id=18,
		playerName="霞客",
		monsterName="[狂暴]恶魔甲虫",
		mapName="迷宫二层",
		itemID=62201,
		itemName="纵横战剑",
		mapX=29,
		mapY=41,
	},
	[19] = { 
		id=19,
		playerName="时珍",
		monsterName="[狂暴]恶魔侍卫",
		mapName="迷宫二层",
		itemID=62202,
		itemName="纵横战甲",
		mapX=30,
		mapY=42,
	},
	[20] = { 
		id=20,
		playerName="继光",
		monsterName="[狂暴]恶魔野人",
		mapName="迷宫二层",
		itemID=62203,
		itemName="纵横战衣",
		mapX=123,
		mapY=12,
	},
	[21] = { 
		id=21,
		playerName="自成",
		monsterName="[狂暴]沃玛战士",
		mapName="迷宫二层",
		itemID=62204,
		itemName="纵横战盔",
		mapX=124,
		mapY=13,
	},
	[22] = { 
		id=22,
		playerName="成功",
		monsterName="[狂暴]沃玛勇士",
		mapName="迷宫二层",
		itemID=62205,
		itemName="纵横战链",
		mapX=125,
		mapY=14,
	},
	[23] = { 
		id=23,
		playerName="康熙",
		monsterName="[狂暴]沃玛战将",
		mapName="迷宫二层",
		itemID=62206,
		itemName="纵横战镯",
		mapX=126,
		mapY=15,
	},
	[24] = { 
		id=24,
		playerName="松龄",
		monsterName="[狂暴]火焰沃玛",
		mapName="迷宫二层",
		itemID=62207,
		itemName="纵横战戒",
		mapX=127,
		mapY=16,
	},
	[25] = { 
		id=25,
		playerName="乾隆",
		monsterName="[狂暴]蜈蚣",
		mapName="迷宫二层",
		itemID=62208,
		itemName="纵横战带",
		mapX=128,
		mapY=17,
	},
	[26] = { 
		id=26,
		playerName="雪芹",
		monsterName="[狂暴]混乱守卫",
		mapName="迷宫二层",
		itemID=62209,
		itemName="纵横战靴",
		mapX=129,
		mapY=18,
	},
	[27] = { 
		id=27,
		playerName="则徐",
		monsterName="[狂暴]混乱侍卫",
		mapName="迷宫一层",
		itemID=62210,
		itemName="纵横道扇",
		mapX=130,
		mapY=19,
	},
	[28] = { 
		id=28,
		playerName="慈禧",
		monsterName="[狂暴]混乱卫士",
		mapName="迷宫一层",
		itemID=62211,
		itemName="纵横道甲",
		mapX=131,
		mapY=20,
	},
	[29] = { 
		id=29,
		playerName="国藩",
		monsterName="[狂暴]混乱巫师",
		mapName="迷宫一层",
		itemID=62212,
		itemName="纵横道衣",
		mapX=132,
		mapY=21,
	},
	[30] = { 
		id=30,
		playerName="宗棠",
		monsterName="[狂暴]赤月恶魔",
		mapName="迷宫一层",
		itemID=62213,
		itemName="纵横道盔",
		mapX=133,
		mapY=22,
	},
	[31] = { 
		id=31,
		playerName="秀全",
		monsterName="[狂暴]赤月炎蛇",
		mapName="迷宫一层",
		itemID=62214,
		itemName="纵横道链",
		mapX=134,
		mapY=23,
	},
	[32] = { 
		id=32,
		playerName="鸿章",
		monsterName="[狂暴]赤月蜘蛛",
		mapName="迷宫一层",
		itemID=62215,
		itemName="纵横道镯",
		mapX=135,
		mapY=24,
	},
	[33] = { 
		id=33,
		playerName="雪岩",
		monsterName="[狂暴]赤月魔蝎",
		mapName="迷宫一层",
		itemID=62216,
		itemName="纵横道戒",
		mapX=136,
		mapY=25,
	},
	[34] = { 
		id=34,
		playerName="有为",
		monsterName="[狂暴]赤月蛛王",
		mapName="迷宫一层",
		itemID=62217,
		itemName="纵横道带",
		mapX=137,
		mapY=26,
	},
	[35] = { 
		id=35,
		playerName="天佑",
		monsterName="[狂暴]赤月蝎蛇",
		mapName="幻境一层",
		itemID=62218,
		itemName="纵横道靴",
		mapX=138,
		mapY=27,
	},
	[36] = { 
		id=36,
		playerName="世凯",
		monsterName="[狂暴]地狱守卫",
		mapName="幻境一层",
		itemID=62219,
		itemName="纵横魔刃",
		mapX=232,
		mapY=122,
	},
	[37] = { 
		id=37,
		playerName="白石",
		monsterName="[狂暴]地狱侍卫",
		mapName="幻境一层",
		itemID=62220,
		itemName="纵横魔甲",
		mapX=233,
		mapY=123,
	},
	[38] = { 
		id=38,
		playerName="中山",
		monsterName="[狂暴]地狱使者",
		mapName="幻境一层",
		itemID=62221,
		itemName="纵横魔袍",
		mapX=234,
		mapY=124,
	},
	[39] = { 
		id=39,
		playerName="元培",
		monsterName="[狂暴]地狱魔将",
		mapName="幻境一层",
		itemID=62222,
		itemName="纵横魔盔",
		mapX=235,
		mapY=125,
	},
	[40] = { 
		id=40,
		playerName="独秀",
		monsterName="[狂暴]地狱法师",
		mapName="幻境一层",
		itemID=62223,
		itemName="纵横魔链",
		mapX=236,
		mapY=126,
	},
	[41] = { 
		id=41,
		playerName="鲁迅",
		monsterName="[狂暴]地狱统领",
		mapName="幻境一层",
		itemID=62224,
		itemName="纵横魔镯",
		mapX=237,
		mapY=127,
	},
	[42] = { 
		id=42,
		playerName="四光",
		monsterName="[狂暴]火龙刀兵",
		mapName="幻境一层",
		itemID=62225,
		itemName="纵横魔戒",
		mapX=238,
		mapY=128,
	},
	[43] = { 
		id=43,
		playerName="可桢",
		monsterName="[狂暴]火龙破甲兵",
		mapName="幻境一层",
		itemID=62226,
		itemName="纵横魔带",
		mapX=239,
		mapY=129,
	},
	[44] = { 
		id=44,
		playerName="沫若",
		monsterName="[狂暴]火龙射手",
		mapName="幻境一层",
		itemID=62227,
		itemName="纵横魔靴",
		mapX=240,
		mapY=130,
	},
	[45] = { 
		id=45,
		playerName="悲鸿",
		monsterName="[狂暴]牛魔祭司",
		mapName="幻境一层",
		itemID=62228,
		itemName="纵横勋章",
		mapX=241,
		mapY=131,
	},
}
return config
